# Python assert 关键字，assert 语句

> 原文:[https://codescracker.com/python/python-assert-keyword.htm](https://codescracker.com/python/python-assert-keyword.htm)

Python 中的 **assert** 关键字在我们需要早期检测问题时使用，在程序中 原因是清楚的。例如:

```
print("Enter the Numerator Value: ", end="")
num = int(input())
print("Enter the Denominator Value: ", end="")
den = int(input())

assert den != 0

quot = int(num/den)
print("\nQuotient =", quot)
```

下面给出的快照显示了以用户输入 **20** 作为分子，以 **2** 作为分母的样本运行:

![python assert keyword](../Images/6e470a03f102bcddcd6de876a729d1c4.png)

下面是另一个运行示例，用户输入 **14** 作为分子， **0** 作为分母:

![python assert statement](../Images/881918e915b1e61d26f0bf2d8191e6fe.png)

因为**位**为 0，所以**断言**的条件评估为**假**。因此， 程序执行停止，并在输出上抛出 **AssertionError** 。

**注意-***断言*关键字被使用，基本上是作为一个调试目的，当 出现错误时，它会暂停程序。

上面的程序也可以这样创建:

```
print("Enter the Numerator Value: ", end="")
n = int(input())
print("Enter the Denominator Value: ", end="")
d = int(input())

if not d != 0:
    raise AssertionError()

print("\nQuotient =", int(n/d))
```

您将得到与该程序类似的输出。

## Python assert 语句语法

Python 中 **assert** 语句的语法是:

```
assert condition
```

或者

```
assert condition, error_message
```

在第二种语法中，我们也可以使用 **error_message** 来显示错误。例如:

```
print("Enter the Numerator Value: ", end="")
n = int(input())
print("Enter the Denominator Value: ", end="")
d = int(input())

assert d != 0, "Denominator must not be 0"

print("\nQuotient =", int(n/d))
```

以用户输入 **25** 作为分子，以 **0** 作为分母的示例运行显示在下面给出的快照 中:

![python assert keyword example](../Images/563b426c5cd8a432632c06432451040e.png)

## Python assert 关键字示例

下面是 Python 中的一个 **assert** 语句或关键字的例子:

```
def chkFun(x):
    assert type(x) == int
    print("Yes, 'x' is of 'int' type")
    print("The value is:", x)

chkFun(100)

chkFun('a')

chkFun(10)
```

下面给出的快照显示了其示例输出:

![python assert statement example](../Images/e797d3e798dc350fb9cd9b675045dac4.png)

也就是说，在名为 **chkFun()** 的函数中，第一次传递的参数 **100** 属于 **int** 类型，因此 **type(x) == int** 求值为 **True** ，并且执行两个 **print()** 语句。

但是对于 **chkFun()** 函数的第二次调用，传递的参数**‘a’**不是 **int** 类型，因此 **type(x) == int** 求值为 **False** ，程序停止，并出现 **AssertionError**

[Python 在线测试](/exam/showtest.php?subid=10)

* * *

* * *