# 使用递归打印乘法表的 Python 程序

> 原文:[https://codescracker . com/python/program/python-print-table . htm](https://codescracker.com/python/program/python-print-table.htm)

本文介绍了用 Python 编写的程序，利用 递归函数查找并[打印一个数](python-program-print-multiplication-table.htm)的乘法表。该数字必须由用户在运行时输入。

## 使用递归打印表格

问题是，*写一个 Python 程序，用递归打印给定数字的表格。下面给出的程序是这个问题的答案:*

```
def tab_rec_fun(n, i):
    if(i>10):
        return
    print(n, "*", i, "=", n*i)
    return tab_rec_fun(n, i+1)

print("Enter the Number: ")
num = int(input())
print("\nTable of", num, "is:")
tab_rec_fun(num, 1)
```

以下是上述 Python 程序产生的初始输出:

![print multiplication table python](../Images/846c7cddf5289f21257cbd5203afa8a4.png)

现在提供输入，比如说 **6** 作为数字，使用 Python 中的递归函数查找并打印它的表，就像下面给出的示例输出中的 :

![print multiplication of number python](../Images/6c951f99862be2455315d0801f02d761.png)

#### 先前程序的修改版本

在这个程序中，我使用了 **try-except** 块来处理和提供用户 试图输入任何无效输入时的手动错误消息。其余的事情和之前的程序差不多。

```
def tableFun(n, i):
    if(i>10):
        return
    print(n, "*", i, "=", n*i)
    return tableFun(n, i+1)

print("Enter a Number: ", end="")
try:
    num = int(input())
    print("\n-------Table of", num, "--------")
    tableFun(num, 1)
except ValueError:
    print("\nInvalid Input!")
```

下面是用户输入的示例运行， **132** :

![python print multiplication table](../Images/441f4bec0828703075f832b39f89feeb.png)

这是另一个使用用户输入 **c** 运行的示例:

![python print table using recursion](../Images/dfe75b5cd1b83d7720f33b1ad47127ea.png)

[Python 在线测试](/exam/showtest.php?subid=10)

* * *

* * *