# JavaScript 异常处理

> 原文:[https://codescracker.com/js/js-exception-handling.htm](https://codescracker.com/js/js-exception-handling.htm)

众所周知，异常是在程序语法正确时，由于非法操作而在执行时发生的错误。

## JavaScript 中处理异常的方法

您可以通过以下两种方式在 JavaScript 中处理异常:

*   使用 [try-catch 语句](/js/js-errors.htm)
*   使用 [onerror 事件](/js/js-onerror-event.htm)

## 使用 try-catch 的异常处理

下面的示例演示了如何在 JavaScript 中使用 try-catch 语句处理异常:

```
<!DOCTYPE HTML>
<html>
<head>
   <title>JavaScript Exception Handling</title>
   <script type="text/javascript">
      try
      {
         document.write(val);
         document.write("Hello World!, This is Exception Handling.");
      }
      catch(err)
      {
         document.write(err.message);
      }
   </script>
</head>
<body>

</body>
</html>
```

从上面的 JavaScript 异常处理示例中可以看出，变量 **val** 没有定义，因此在执行了上面的异常处理示例后，下面是您将在浏览器中看到的 输出:

![javascript exception handling](../Images/3bb101fc6fadd7264254759f7c196409.png)

这是 JavaScript 中异常处理的另一个例子。这个异常处理的例子使用了另一个叫做 **finally** 的块，它与 try-catch 语句相关联。不管 是否抛出异常，try-catch 语句的 finally 块总是运行它的代码。下面是 JavaScript 中上述异常处理示例的修改版本:

```
<!DOCTYPE HTML>
<html>
<head>
   <title>JavaScript Exception Handling</title>
   <script type="text/javascript">
      try
      {
         document.write(val);
      }
      catch(err)
      {
         document.write(err.message);
      }
      finally
      {
         document.write("<br/>");
         document.write("Hello World!, This is Exception Handling.");
      }
   </script>
</head>
<body>

</body>
</html>
```

下面是上面的 JavaScript 异常处理示例产生的示例输出:

![javascript exception handling example](../Images/5f390a5717132c439bd9ee638e1e7b82.png)

## 使用 onerror 事件的 JavaScript 异常处理

以下是 JavaScript 中使用 onerror 事件进行异常处理的示例:

```
<!DOCTYPE HTML>
<html>
<head>
   <title>JavaScript Exception Handling</title>
   <script type="text/javascript">
      window.onerror = function(ermessage, url, line)
      {
         document.write(ermessage+"<br/>");
         document.write(url+"<br/>");
         document.write(line+"<br/>");
      }
      document.write(val);
   </script>
</head>
<body>

</body>
</html>
```

下面是使用 onerror 事件示例代码的上述 JavaScript 异常处理产生的示例输出:

![javascript exception handling using onerror event](../Images/ca0fadb294430bbd634919f93c043373.png)

[JavaScript 在线测试](/exam/showtest.php?subid=6)

* * *

* * *