# JavaScript try catch throw 最后

> 原文：<https://codescracker.com/js/js-errors.htm>

您可以使用 try-catch 语句以专业的方式编写 JavaScript 代码。在 JavaScript 中使用 try-catch 语句意味着在 try 块中编写会产生错误的 JavaScript 代码。紧接着，在 try 块之后，有一个 catch 块，它指定了您想要捕获的异常类型。

下面是 JavaScript 中 try-catch 语句的一般形式:

```
try
{
   // JavaScript code that may cause an error
}
catch
{
   // code to execute on finding some errors in the code 
   // written in try block
}
```

您可以使用 JavaScript throw 语句来定义自定义错误。以下是 JavaScript throw 语句的一个示例:

```
throw "It is too much";
throw 300;
```

您可以使用 JavaScript finally 块来执行放置在 finally 块中的代码，而不管错误是否发生。下面是 JavaScript finally 块的一般形式:

```
try
{
    // JavaScript code to be executed first
}
catch(err)
{
    // JavaScript code to handle errors caused in the code of try block
}
finally
{
    // JavaScript code to execute regardless the result of try-catch block
}
```

[JavaScript 在线测试](/exam/showtest.php?subid=6)

* * *

* * *