# Java 异常子类

> 原文:[https://codescracker . com/Java/Java-creating-exception-subclass . htm](https://codescracker.com/java/java-creating-exception-subclasses.htm)

尽管 Java 的内置异常处理最常见的错误，但是您可能希望创建自己的异常类型来管理特定于您的应用程序的情况。这很容易做到:
只需定义**异常**的一个子类(可抛出的**的一个子类)。你的子类实际上不需要实现任何东西，它们在类型系统中的存在允许你把它们作为异常来使用。**

## Java 异常类

**异常**类没有定义自己的任何方法。它继承了由 **Throwable** 提供的那些方法。因此，所有的异常，包括你创建的那些，都有由 **Throwable** 定义的方法。它们显示在接下来的表格中。您可能还想在自己创建的异常类中重写这些方法中的一个或多个。

**异常**定义了四个公共构造函数，其中两个构造函数支持 (你将在下一章了解链式异常)， 和另外两个构造函数如下所示:

```
Exception()
Exception(String *msg*)
```

第一种形式创建一个没有描述的异常。第二种形式允许您指定异常的描述。

尽管在创建异常时指定描述通常很有用，但有时最好覆盖方法 **toString()** 。 作为由 **Throwable** 定义的 **toString()** 方法的版本(并由 **Exception** 继承)，首先显示异常的名称 ，后跟冒号，然后是您的描述。通过覆盖方法 **toString()** ， 可以防止显示异常名称和冒号。这有助于更干净的输出，这在某些情况下是可取的。

### Throwable 定义的方法

这里，下表列出了 Throwable 定义的方法:

| 方法 | 描述 |
| 最终 void add suppressed(Throwable*exc*) | 将 *exc* 添加到与调用异常相关的隐藏异常列表中。主要供 **try** -with-resources 语句使用 |
| Throwable fillInStackTrace() | 返回一个包含完整堆栈跟踪的可抛出对象。这个对象可以被再次抛出 |
| Throwable getCause() | 返回当前异常的基础异常。如果没有底层异常，则返回空值 |
| String getLocalizedMessage() | 返回异常的本地化描述 |
| 字符串 getMessage() | 返回异常的描述 |
| StackTraceElement[] getStackTrace | 返回包含堆栈跟踪的数组，一次一个元素，作为 **StackTraceElement** 的数组。栈顶的方法 是抛出异常前最后调用的方法。该方法位于数组的第一个元素中。 **StackTraceElement**类让您的程序可以访问跟踪中每个元素的信息，比如它的方法名 |
| final Throwable[] getSuppressed() | 获取与调用异常关联的隐藏异常，并返回包含结果的数组。被抑制的异常主要由 **try** -with-resources 语句生成 |
| Throwable init cause(Throwable*cause exc* | 将 *causeExc* 与调用异常相关联，作为调用异常的原因。返回对异常的引用 |
| void printStackTrace() | 显示堆栈跟踪 |
| void printStackTrace(PrintStream*stream* | 将堆栈跟踪发送到指定的流 |
| void printStackTrace(PrintWriter*流* | 将堆栈跟踪发送到指定的流 |
| void setStackTrace(StackTraceElement*elements*[]) | 将堆栈跟踪设置为在*元素*中传递的元素。这种方法是为专门的应用，而不是正常使用 |
| toString()字符串 | 返回一个包含异常描述的**字符串**对象。当 输出一个**可抛出的**对象时，这个方法被 **println()** 调用 |

## Java 异常子类示例

在这里，这个示例程序声明了一个新的**异常**的子类，然后使用这个子类在一个方法中发出一个错误条件的信号。它 覆盖了方法 **toString()** ，允许显示异常的简单明了的描述。

```
/* Java Program Example - Java Create Exception Subclasses
 * This program creates a custom exception type 
 */

 class MyException extends Exception {
     private int detail;

     MyException(int x) {
         detail = x;
     }

     public String toString() {
         return "MyException[" + detail + "]";
     }
 }

 class JavaProgram
 {

     static void calculate(int x) throws MyException {

         System.out.println("Called calculate(" + x + ")");

         if(x>10)
            throw new MyException(x);

         System.out.println("Normal exit");

     }
     public static void main(String args[])
     {

         try {

             calculate(1);
             calculate(30);

         } catch(MyException e) {

             System.out.println("Caught " + e);

         }

     }
 }
```

这个示例程序定义了一个名为 **MyException** 的**异常**的子类。这个子类最好是简单的。因为它只有 一个构造函数和一个显示异常值的覆盖方法 **toString()** 。类 **JavaProgram** 定义了一个 **calculate()** 方法，该方法抛出 **MyException** 对象。当 **calculate()** 方法的整数参数大于 10 时抛出异常。方法 **main()** 为 **MyException** 设置了一个异常处理程序，然后 用一个有效值(小于 10)和一个非法值调用方法 **calculate()** 以通过代码显示两条路径。以下是输出/结果:

![java create exception subclasses](../Images/cf9e0ccb9741c15c2bb3a1f77892f7ae.png)

[Java 在线测试](/exam/showtest.php?subid=1)

* * *

* * *