# Java 链式异常

> 原文:[https://codescracker.com/java/java-chained-exceptions.htm](https://codescracker.com/java/java-chained-exceptions.htm)

使用*链式异常*特性，您可以将另一个异常与一个异常相关联。第二个异常说明了第一个异常 的起因。例如，想象一种情况，其中一个方法因为试图 被零除而抛出一个**算术异常**。然而，问题的实际原因是发生了 I/O 错误，这导致除数设置不正确。

尽管该方法肯定会抛出一个**算术异常**，但由于这是发生的错误，您可能希望让 调用代码知道潜在的原因是一个 I/O 错误。链式异常允许您管理这种情况，以及任何其他存在 层异常的情况。

### Java 中如何允许链式异常？

为了允许 Java 中的链式异常，在 **Throwable** 中添加了两个构造函数和两个方法。这里显示了构造函数:

```
Throwable(Throwable *causeExc*)
Throwable(String *msg*, Throwable *causeExc*)
```

在第一种形式中， *causeExc* 是异常，导致当前异常，即 *causeExc* 是异常 发生的根本原因。第二种形式允许您在指定异常原因的同时指定描述。这两个 构造函数也被添加到了**错误、异常**和**运行时异常**类中。

方法 **getCause()** 和 **initCause()** 是 **Throwable** 支持的链式异常方法。这些方法如表 所示(在前一章),为了便于讨论，在此重复。

```
Throwable getCause()
Throwable initCause(Throwable *causeExc*)
```

方法 **getCause()** 返回当前异常的基础异常。如果没有底层异常，**返回 null** 。

方法 **initCause()** 将 *causeExc* 与调用异常相关联，并返回对异常的引用。因此，在创建异常后，您可以 将原因与异常相关联。然而，原因异常只能设置一次。因此， 对于每个异常对象，只能调用 **initCause()** 一次。此外，如果原因异常是由构造函数设置的，那么您 不能使用 **initCause()** 再次设置它。

一般来说， **initCause()** 用于为不支持前面描述的两个额外的 构造函数的遗留异常类设置原因。

## Java 链式异常示例

下面是一个示例程序，演示了处理链式异常的机制

```
/* Java Program Example - Java Chained Exceptions
*  This program demonstrates the exception chaining   */

 class JavaProgram
 {
     static void demometh()
     {
         /* creating an exception */
         NullPointerException e = new NullPointerException("top layer");

         /* add a cause */
         e.initCause(new ArithmeticException("cause"));

         throw e;
     }

     public static void main(String args[])
     {

         try
       {
             demometh();
         }
       catch(NullPointerException e)
       {
             /* display the top level exception */
             System.out.println("caught : " + e);

             /* display the cause exception */
             System.out.println("original cause : " + e.getCause());
         }

     }
 }
```

当编译并执行上述 Java 程序时，它将产生以下输出:

![java chained exceptions](../Images/cad45da465c627802c29b21bfa3f4efc.png)

在本例中， **NullPointerException** 是顶级异常。添加了一个原因异常，**算法异常**。 当异常从 **demometh()** 方法中抛出时，它被 **main()** 捕获。在那里，显示了顶级异常， 之后是底层异常，它是通过调用方法 **getCause()** 获得的。

链式异常可以进行到任何必要的深度。因此，原因异常本身可以有一个原因。请注意，过长的异常链可能显示出糟糕的设计。

链式异常并不是每个程序都需要的。然而，在潜在原因的知识是有用的情况下，他们提供了一个优雅的解决方案。

[Java 在线测试](/exam/showtest.php?subid=1)

* * *

* * *